name: Auditoria sobre diverses versions de Python

on:
  push:
    branches: [ "main" ]

jobs:
  test-security:
    name: Test en Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    # ESTRATÈGIA DE MATRIU
    strategy:
      matrix:
        # Aquí definim les variants que volem provar
        python-version: ["3.10", "3.11", "3.12"]  # <-- Crearem 3 jobs

    steps:
    - name: Checkout del codi
      uses: actions/checkout@v4

    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        # La versió depèn de la variable de la matriu
        python-version: ${{ matrix.python-version }}

    - name: Instal·lar dependències
      run: |
        pip install -r requirements.txt

    - name: Executar Tests Automatitzats
      run: |
        python manage.py test
